version: '3.9'

services:
  node:
    container_name: node-application-node
    build: ./node
    volumes:
      - ./node:/usr/src/app
    ports:
      - 8080:8080

  postgres:
    container_name: node-application-postgres
    build: ./postgresql
    volumes: 
      - db:/var/lib/postgresql/data
      - ./postgresql/scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

volumes:
  db:
    driver: local